---

_You are currently looking at **version 1.5** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

# Assignment 3 - More Pandas
This assignment requires more individual learning then the last one did - you are encouraged to check out the [pandas documentation](http://pandas.pydata.org/pandas-docs/stable/) to find functions or methods you might not have used yet, or ask questions on [Stack Overflow](http://stackoverflow.com/) and tag them as pandas and python related. And of course, the discussion forums are open for interaction with your peers and the course staff.

### Question 1 (20%)
Load the energy data from the file `Energy Indicators.xls`, which is a list of indicators of [energy supply and renewable electricity production](Energy%20Indicators.xls) from the [United Nations](http://unstats.un.org/unsd/environment/excel_file_tables/2013/Energy%20Indicators.xls) for the year 2013, and should be put into a DataFrame with the variable name of **energy**.

Keep in mind that this is an Excel file, and not a comma separated values file. Also, make sure to exclude the footer and header information from the datafile. The first two columns are unneccessary, so you should get rid of them, and you should change the column labels so that the columns are:

`['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']`

Convert `Energy Supply` to gigajoules (there are 1,000,000 gigajoules in a petajoule). For all countries which have missing data (e.g. data with "...") make sure this is reflected as `np.NaN` values.

Rename the following list of countries (for use in later questions):

```"Republic of Korea": "South Korea",
"United States of America": "United States",
"United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
"China, Hong Kong Special Administrative Region": "Hong Kong"```

There are also several countries with numbers and/or parenthesis in their name. Be sure to remove these, 

e.g. 

`'Bolivia (Plurinational State of)'` should be `'Bolivia'`, 

`'Switzerland17'` should be `'Switzerland'`.

<br>

Next, load the GDP data from the file `world_bank.csv`, which is a csv containing countries' GDP from 1960 to 2015 from [World Bank](http://data.worldbank.org/indicator/NY.GDP.MKTP.CD). Call this DataFrame **GDP**. 

Make sure to skip the header, and rename the following list of countries:

```"Korea, Rep.": "South Korea", 
"Iran, Islamic Rep.": "Iran",
"Hong Kong SAR, China": "Hong Kong"```

<br>

Finally, load the [Sciamgo Journal and Country Rank data for Energy Engineering and Power Technology](http://www.scimagojr.com/countryrank.php?category=2102) from the file `scimagojr-3.xlsx`, which ranks countries based on their journal contributions in the aforementioned area. Call this DataFrame **ScimEn**.

Join the three datasets: GDP, Energy, and ScimEn into a new dataset (using the intersection of country names). Use only the last 10 years (2006-2015) of GDP data and only the top 15 countries by Scimagojr 'Rank' (Rank 1 through 15). 

The index of this DataFrame should be the name of the country, and the columns should be ['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations',
       'Citations per document', 'H index', 'Energy Supply',
       'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015'].

*This function should return a DataFrame with 20 columns and 15 entries.*

In [1]:
'awefewfasfd (wegfdgag)'.partition('(')[0].strip()

'awefewfasfd'

In [2]:
def answer_one():
    import pandas as pd
    #
    def energy():
        import pandas as pd
        import numpy as np
        #readdata
        energy = pd.read_excel('Energy Indicators.xls')
        energy = energy.iloc[16:243,[1,3,4,5]]
        columnsnames = ['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']
        for i in range(len(energy.columns)):
            energy = energy.rename(columns = {energy.columns[i]:columnsnames[i]})
        
        #remove any digits in the contry column
        chars_notinnums = []    
        for num in range(len(energy['Country'])):
            chars = list(energy['Country'].iloc[num])
            chars_notinnum = [char for char in chars if not char.isdigit()]
            chars_notinnums.append(''.join(chars_notinnum))
        energy['Country'] = chars_notinnums
        
        #replace all entries with '...' with np.NaN
        for i in range(len(energy.columns)):
            energy.iloc[:,i][energy.iloc[:,i] == '...'] = np.NaN
        #conver 'Energy Supply' values to giga_juols
        energy['Energy Supply'] *= 1000000
        #replace each country in dict's keys with the correspoinding dicts values
        dicts = {"Republic of Korea": "South Korea",
                "United States of America": "United States",
               "United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
               "China, Hong Kong Special Administrative Region": "Hong Kong"}
        energy['Country'] = energy['Country'].replace(dicts)
        #remove the part after'(' form all countries that have parenthesis
        for i in range(len(energy)):
            energy.iloc[i,0]=energy.iloc[i,0].partition('(')[0]
            
        energy['Country'] = energy['Country'].replace({'Iran ' : 'Iran'})
        
        
        for i in range(1,len(energy.columns)):
            energy.iloc[:,i]=energy.iloc[:,i].astype('float64')
        energy = energy.reset_index()
        
        return energy
    
    def gdp():
        
        import pandas as pd
        #read data
        GDP = pd.read_csv('world_bank.csv',header = 4)
        #replace each country in dicts's keys with the corresponding dicts values
        dicts = {"Korea, Rep.": "South Korea",
                 "Iran, Islamic Rep.": "Iran",
                 "Hong Kong SAR, China": "Hong Kong"}
        GDP['Country Name'] = GDP['Country Name'].replace(dicts)
        #change column name 'Country Name' to 'Country'
        GDP = GDP.rename(columns = {'Country Name':'Country'})
        #keep only the column['Country', '2006', '2007', '2008','2009','2010', '2011','2012','2013','2014','2015']
        GDP = GDP[['Country', '2006', '2007', '2008','2009','2010', '2011','2012','2013','2014','2015']]
        return GDP
    def scimen():
        import pandas as pd
        ScimEn = pd.read_excel('scimagojr-3.xlsx')
        return ScimEn
    energy = energy()
    GDP = gdp()
    ScimEn = scimen()
    tdf = pd.merge(energy,ScimEn,how = 'right', left_on = 'Country', right_on='Country')
    tdf = pd.merge(GDP,tdf, how = 'right',left_on = 'Country', right_on='Country')
    res = tdf[tdf['Rank'] <= 15]
    res = res.set_index('Country')
    del res['index']
    return res

In [3]:
answer_one()

,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,Energy Supply,Energy Supply per Capita,% Renewable,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index
Country,,,,,,,,,,,,,,,,,,,,
Australia,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12,5.386000e+09,231.0,11.810810,14,8831,8725,90765,15606,10.28,107
Brazil,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12,1.214900e+10,59.0,69.648030,15,8668,8596,60702,14396,7.00,86
Canada,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12,1.043100e+10,296.0,61.945430,6,17899,17620,215003,40930,12.01,149
China,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,1.271910e+11,93.0,19.754910,1,127050,126767,597237,411683,4.70,138
Germany,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12,1.326100e+10,165.0,17.901530,7,17027,16831,140566,27426,8.26,126
Spain,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12,4.923000e+09,106.0,37.968590,12,9428,9330,123336,23964,13.08,115
France,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12,1.059700e+10,166.0,17.020280,9,13153,12973,130632,28601,9.93,114
United Kingdom,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12,7.920000e+09,124.0,10.600470,4,20944,20357,206091,37874,9.84,139
India,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,3.319500e+10,26.0,14.969080,8,15005,14841,128763,37209,8.58,115
Iran,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN,9.172000e+09,119.0,5.707721,13,8896,8819,57470,19125,6.46,72
Italy,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12,6.530000e+09,109.0,33.667230,11,10964,10794,111850,26661,10.20,106
Japan,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,1.898400e+10,149.0,10.232820,3,30504,30287,223024,61554,7.31,134
South Korea,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12,1.100700e+10,221.0,2.279353,10,11983,11923,114675,22595,9.57,104
Russian Federation,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,3.070900e+10,214.0,17.288680,5,18534,18301,34266,12422,1.85,57
United States,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,9.083800e+10,286.0,11.570980,2,96661,94747,792274,265436,8.20,230

### Question 2 (6.6%)
The previous question joined three datasets then reduced this to just the top 15 entries. When you joined the datasets, but before you reduced this to the top 15 items, how many entries did you lose?

*This function should return a single number.*

In [4]:
%%HTML
<svg width="800" height="300">
  <circle cx="150" cy="180" r="80" fill-opacity="0.2" stroke="black" stroke-width="1" fill="blue" />
  <circle cx="200" cy="100" r="80" fill-opacity="0.2" stroke="black" stroke-width="1" fill="red" />
  <circle cx="100" cy="100" r="80" fill-opacity="0.2" stroke="black" stroke-width="1" fill="green" />
  <line x1="150" y1="125" x2="300" y2="150" stroke="black" stroke-width="2" fill="black" stroke-dasharray="5,3"/>
  <text  x="300" y="165" font-family="Verdana" font-size="35">Everything but this!</text>
</svg>

In [5]:

def answer_two():
    import pandas as pd
    #
    def energy():
        import pandas as pd
        import numpy as np
        #readdata
        energy = pd.read_excel('Energy Indicators.xls')
        energy = energy.iloc[16:243,[1,3,4,5]]
        columnsnames = ['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']
        for i in range(len(energy.columns)):
            energy = energy.rename(columns = {energy.columns[i]:columnsnames[i]})
        
        #remove any digits in the contry column
        chars_notinnums = []    
        for num in range(len(energy['Country'])):
            chars = list(energy['Country'].iloc[num])
            chars_notinnum = [char for char in chars if not char.isdigit()]
            chars_notinnums.append(''.join(chars_notinnum))
        energy['Country'] = chars_notinnums
        
        #replace all entries with '...' with np.NaN
        for i in range(len(energy.columns)):
            energy.iloc[:,i][energy.iloc[:,i] == '...'] = np.NaN
        #conver 'Energy Supply' values to giga_juols
        energy['Energy Supply'] *= 1000000
        #replace each country in dict's keys with the correspoinding dicts values
        dicts = {"Republic of Korea": "South Korea",
                "United States of America": "United States",
               "United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
               "China, Hong Kong Special Administrative Region": "Hong Kong"}
        energy['Country'] = energy['Country'].replace(dicts)
        #remove the part after'(' form all countries that have parenthesis
        for i in range(len(energy)):
            energy.iloc[i,0]=energy.iloc[i,0].partition('(')[0]
            
        energy['Country'] = energy['Country'].replace({'Iran ' : 'Iran'})
        
        
        for i in range(1,len(energy.columns)):
            energy.iloc[:,i]=energy.iloc[:,i].astype('float64')
        energy = energy.reset_index()
        
        return energy
    
    def gdp():
        
        import pandas as pd
        #read data
        GDP = pd.read_csv('world_bank.csv',header = 4)
        #replace each country in dicts's keys with the corresponding dicts values
        dicts = {"Korea, Rep.": "South Korea",
                 "Iran, Islamic Rep.": "Iran",
                 "Hong Kong SAR, China": "Hong Kong"}
        GDP['Country Name'] = GDP['Country Name'].replace(dicts)
        #change column name 'Country Name' to 'Country'
        GDP = GDP.rename(columns = {'Country Name':'Country'})
        #keep only the column['Country', '2006', '2007', '2008','2009','2010', '2011','2012','2013','2014','2015']
        GDP = GDP[['Country', '2006', '2007', '2008','2009','2010', '2011','2012','2013','2014','2015']]
        return GDP
    def scimen():
        import pandas as pd
        ScimEn = pd.read_excel('scimagojr-3.xlsx')
        return ScimEn
    energy = energy()
    GDP = gdp()
    ScimEn = scimen()
    tdf = pd.merge(energy,ScimEn,how = 'inner', left_on = 'Country', right_on='Country')
    tdf = pd.merge(GDP,tdf, how = 'inner',left_on = 'Country', right_on='Country')
#     res = tdf[tdf['Rank'] <= 15]
#     res = res.set_index('Country')
    
    tdf_out = pd.merge(energy,ScimEn,how = 'outer', left_on = 'Country', right_on='Country')
    tdf_out = pd.merge(GDP,tdf, how = 'outer',left_on = 'Country', right_on='Country')
#     res_out = tdf_out[tdf_out['Rank'] <= 15]
#     res_out = res_out.set_index('Country')   
    
    
    return len(tdf_out)-len(tdf)

In [6]:
answer_two()

103

<br>

Answer the following questions in the context of only the top 15 countries by Scimagojr Rank (aka the DataFrame returned by `answer_one()`)

### Question 3 (6.6%)
What is the average GDP over the last 10 years for each country? (exclude missing values from this calculation.)

*This function should return a Series named `avgGDP` with 15 countries and their average GDP sorted in descending order.*

In [7]:
def answer_three():
    Top15 = answer_one()
    import numpy as np
    
    avgGDP = Top15[['2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014',
       '2015']].mean(axis=1).sort_values(ascending = False)
    return avgGDP

### Question 4 (6.6%)
By how much had the GDP changed over the 10 year span for the country with the 6th largest average GDP?

*This function should return a single number.*

In [8]:
def answer_four():
    Top15 = answer_one()    
    avgGDP = Top15[['2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014',
       '2015']].mean(axis=1).sort_values(ascending = False)
    avgGDP_6th = avgGDP.index[5]
    diff = Top15.loc[avgGDP_6th,'2015'] - Top15.loc[avgGDP_6th,'2006']
    return diff

### Question 5 (6.6%)
What is the mean `Energy Supply per Capita`?

*This function should return a single number.*

In [9]:
def answer_five():
    Top15 = answer_one()
    import pandas as pd
    answer = Top15['Energy Supply per Capita'].mean()
    return answer

### Question 6 (6.6%)
What country has the maximum % Renewable and what is the percentage?

*This function should return a tuple with the name of the country and the percentage.*

In [10]:
def answer_six():
    Top15 = answer_one()
    country_max = Top15['% Renewable'].idxmax()
    max_renewable = Top15['% Renewable'][country_max]
    answer = country_max, max_renewable
    return answer

### Question 7 (6.6%)
Create a new column that is the ratio of Self-Citations to Total Citations. 
What is the maximum value for this new column, and what country has the highest ratio?

*This function should return a tuple with the name of the country and the ratio.*

In [11]:
def answer_seven():
    Top15 = answer_one()
    ratio_to = Top15['Self-citations'] / Top15['Citations']
    country_maxratio = ratio_to.idxmax()
    maxratio = ratio_to[country_maxratio]
    answer = country_maxratio, maxratio
    
    return answer

### Question 8 (6.6%)

Create a column that estimates the population using Energy Supply and Energy Supply per capita. 
What is the third most populous country according to this estimate?

*This function should return a single string value.*

In [12]:
def answer_eight():
    Top15 = answer_one()
    pop = Top15['Energy Supply']/Top15['Energy Supply per Capita']
    answer = pop.sort_values(ascending=False).index[2]
    
    return answer

### Question 9 (6.6%)
Create a column that estimates the number of citable documents per person. 
What is the correlation between the number of citable documents per capita and the energy supply per capita? Use the `.corr()` method, (Pearson's correlation).

*This function should return a single number.*

*(Optional: Use the built-in function `plot9()` to visualize the relationship between Energy Supply per Capita vs. Citable docs per Capita)*

In [13]:
def answer_nine():
    Top15 = answer_one()
    Top15['popest'] = Top15['Energy Supply']/Top15['Energy Supply per Capita']
    Top15['citable ducuments per person'] = Top15['Citable documents'] / Top15['popest']
    import pandas as pd
    corr = pd.merge(pd.DataFrame(Top15['Energy Supply per Capita']),pd.DataFrame(Top15['citable ducuments per person']),how = 'inner',left_index = True,right_index =True).corr(method = 'pearson')
    answer = corr.iloc[0,1]
    return answer

In [14]:
#plot9() # Be sure to comment out plot9() before submitting the assignment!

### Question 10 (6.6%)
Create a new column with a 1 if the country's % Renewable value is at or above the median for all countries in the top 15, and a 0 if the country's % Renewable value is below the median.

*This function should return a series named `HighRenew` whose index is the country name sorted in ascending order of rank.*

In [15]:
def answer_ten():
    Top15 = answer_one()
    Top15.loc[Top15['% Renewable'] >= Top15['% Renewable'].median(),'upmedian'] = 1
    Top15.loc[Top15['% Renewable'] < Top15['% Renewable'].median(),'upmedian'] = 0
    HighRenew = Top15['upmedian'].astype('int64')
    return HighRenew

### Question 11 (6.6%)
Use the following dictionary to group the Countries by Continent, then create a dateframe that displays the sample size (the number of countries in each continent bin), and the sum, mean, and std deviation for the estimated population of each country.

```python
ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}
```

*This function should return a DataFrame with index named Continent `['Asia', 'Australia', 'Europe', 'North America', 'South America']` and columns `['size', 'sum', 'mean', 'std']`*

In [22]:
def answer_eleven():
    import pandas as pd
    Top15 = answer_one()
    country = Top15.index.tolist()
    Top15.reset_index(inplace=True)
    ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}
    Top15['Country'].replace(ContinentDict,inplace=True)
    Top15.rename(columns = {'Country':'Continent'},inplace=True)
    Top15['Country'] = country
    Top15_new = pd.DataFrame()
    Top15_new['size'] = Top15[['Continent','2006', '2007', '2008', '2009', '2010', '2011', '2012',
       '2013', '2014', '2015']].set_index('Continent').groupby(level = 0).count().iloc[:,0]
    Top15_new['sum'] = Top15[['Continent','2006', '2007', '2008', '2009', '2010', '2011', '2012',
       '2013', '2014', '2015']].set_index('Continent').groupby(level = 0).sum().iloc[:,0]
    Top15_new['mean'] = Top15[['Continent','2006', '2007', '2008', '2009', '2010', '2011', '2012',
       '2013', '2014', '2015']].set_index('Continent').groupby(level = 0).mean().iloc[:,0]
    Top15_new['std'] = Top15[['Continent','2006', '2007', '2008', '2009', '2010', '2011', '2012',
       '2013', '2014', '2015']].set_index('Continent').groupby(level = 0).std().iloc[:,0]
    Top15_new = Top15_new.astype('float64')
    answer = Top15_new
    return answer

### Question 12 (6.6%)
Cut % Renewable into 5 bins. Group Top15 by the Continent, as well as these new % Renewable bins. How many countries are in each of these groups?

*This function should return a __Series__ with a MultiIndex of `Continent`, then the bins for `% Renewable`. Do not include groups with no countries.*

In [18]:
def answer_twelve():

    Top15 = answer_one()
    ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}
    import pandas as pd
    Top15['Continent'] = Top15.index
    Top15['Continent'] = Top15['Continent'].replace(ContinentDict)
    Top15['cut%'] = pd.cut(Top15['% Renewable'],5)
    a = Top15.groupby(by = ['Continent']).count().iloc[:,0]
    a=pd.DataFrame(a)
    answer = a.loc[a['2006'].isna() != True,'2006']
    
    return answer

### Question 13 (6.6%)
Convert the Population Estimate series to a string with thousands separator (using commas). Do not round the results.

e.g. 317615384.61538464 -> 317,615,384.61538464

*This function should return a Series `PopEst` whose index is the country name and whose values are the population estimate string.*

In [19]:
def answer_thirteen():
    Top15 = answer_one()
    import pandas as pd
    Top15['PopEst'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    PopEst = Top15['PopEst'].apply(lambda x :"{:,}".format(x)).astype('str')
    
    return PopEst

### Optional

Use the built in function `plot_optional()` to see an example visualization.

In [20]:
#plot_optional() # Be sure to comment out plot_optional() before submitting the assignment!